#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Motor,  port2,           rightFrontMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightBackMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftBackMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	turnFlashlightOn(flashlight);
  wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

  int threshold = 505;      /* found by taking a reading on both DARK and LIGHT    */
                            /* surfaces, adding them together, then dividing by 2. */
  while(true)
  {

    // RIGHT sensor sees dark:
    if(SensorValue(lineFollowerRIGHT) > 2700)
    {
      // counter-steer right:
      motor[leftFrontMotor]  = -60;
      motor[rightFrontMotor] = 60;
      motor[leftBackMotor] = -60;
      motor[rightBackMotor] = 60;
      wait(0.1);
      stopMotor(leftBackMotor);
      stopMotor(rightBackMotor);
      stopMotor(rightFrontMotor);
      stopMotor(leftFrontMotor);
    wait(0.2);
    }
    // CENTER sensor sees dark:
    if(SensorValue(lineFollowerCENTER) < 2600)
    {
      // go straight
      motor[leftFrontMotor] = 20;
      motor[rightFrontMotor] = 20;
      motor[leftBackMotor] = 20;
      motor[rightBackMotor] = 20;
    }
    // LEFT sensor sees dark:
    if(SensorValue(lineFollowerLEFT) > 2730)
    {
      // counter-steer left:
      motor[leftFrontMotor]  = 60;
      motor[rightFrontMotor] = -60;
      motor[leftBackMotor]  = 60;
      motor[rightBackMotor] = -60;
      wait(0.1);
      stopMotor(leftBackMotor);
      stopMotor(rightBackMotor);
      stopMotor(rightFrontMotor);
      stopMotor(leftFrontMotor);
      wait(0.2);
    }
  }
}
