#pragma config(Sensor, dgtl1,  sendSig,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  receiveSig,     sensorTouch)
#pragma config(Sensor, dgtl3,  limitSwitch,    sensorTouch)
#pragma config(Motor,  port1,           myMotor,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if (SensorValue[dgtl3]==1)
		{
			SensorValue[dgtl1]=1;
		}
		else
		{
			SensorValue[dgtl1]=0;
		}
		if (SensorValue[dgtl2]==1)
		{
			startMotor(port1, 127);
		}
		else
		{
		stopMotor(port1);
		}
	}
}
