#pragma config(Sensor, dgtl10, bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port3,           twoMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           threeMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           fourMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           oneMotor,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilBump(bumpSwitch);
	{
		startMotor(oneMotor, 63);
		startMotor(threeMotor, 63);
		wait(3);
		stopMotor(oneMotor);
		stopMotor(threeMotor);
		startMotor(twoMotor, 63);
		startMotor(fourMotor, -63);
		wait(2);
		stopMotor(twoMotor);
		stopMotor(fourMotor);
		wait(2);
		startMotor(oneMotor, 63);
		startMotor(threeMotor, -63);
		wait(1);
		stopMotor(oneMotor);
		stopMotor(threeMotor);
		startMotor(oneMotor, 63);
		startMotor(threeMotor, 63);
		wait(6);
		stopMotor(oneMotor);
		stopMotor(threeMotor);
		startMotor(oneMotor, -63);
		startMotor(threeMotor, 63);
		wait(1);
		stopMotor(oneMotor);
		stopMotor(threeMotor);
		startMotor(oneMotor, 63);
		startMotor(threeMotor, 63);
		wait(1);
		stopMotor(oneMotor);
		stopMotor(threeMotor);
	}
}
